package com.emp_management.shared.exceptions;

public enum ErrorCode {
    // Auth & Access
    UNAUTHORIZED_ACCESS,
    FORBIDDEN,
    BAD_CREDENTIAL,

    // Employee
    EMPLOYEE_NOT_FOUND,
    EMPLOYEE_ALREADY_EXISTS,
    EMPLOYEE_PROFILE_ALREADY_SUBMITTED,
    EMPLOYEE_PROFILE_ALREADY_VERIFIED,
    EMPLOYEE_PROFILE_PENDING_REVIEW,

    // Documents
    DOCUMENT_REQUIRED,
    DOCUMENT_MISMATCH,
    INVALID_EXPERIENCE_DATES,

    // Leave
    INSUFFICIENT_LEAVE_BALANCE,
    INVALID_LEAVE_REQUEST,

    // General
    INVALID_REQUEST,
    RESOURCE_NOT_FOUND,
    VALIDATION_FAILED,
    UNEXPECTED_ERROR,
}