spring.application.name=Emp_Management


spring.datasource.url=jdbc:mysql://localhost:3306/emp_management_db
spring.datasource.username=root
spring.datasource.password=Shaly@1322


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=hr@wenxttech.com
spring.mail.password=Wenxt@2023

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.office365.com


#app.server.ip=192.168.1.62
#app.server.port=9090
#server.ip=0.0.0.0
server.address=0.0.0.0
server.port=8111

spring.jackson.serialization.fail-on-empty-beans=false

## LOCAL / IP (HTTP)
app.cookie.secure=false
#
## PRODUCTION (HTTPS)
## app.cookie.secure=true

jwt.secret=your_super_secret_key_which_is_long_enough_123456
jwt.expiration-ms=86400000
server.servlet.context-path=/api
file.upload-dir=./uploads/leaves
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB


app.document.upload-dir=./uploads/profile-documents
skillset.upload.dir=./uploads/skills
spring.thymeleaf.prefix=classpath:/template/
spring.thymeleaf.suffix=.html# If this exists, remove it or set to false
spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true



